### ISSUE TITLE
Checklist before preprint/submission

### ISSUE THREAD

**Issue by snacktavish** [McTavishLab/OpenTreeCLO#1]
- [ ] Updated Figure 1 with new data
- [ ] Add a figure re: Jetz
- [ ] Workflow figure?
- [ ] 2022 taxon addition tree
- [ ] 2023 taxon addition tree
- [ ] Cleanup and post data files to https://github.com/snacktavish/BirdTree_data (move to McTavishLab for greater professionalism :thinking: ?)
- [ ] Cleanup and post processing code to this repo
- [ ] Manuscript approval by co-authors
